package entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table PHOTO.
 */
public class Photo {

    private Long id;
    private String annotation;
    /** Not-null value. */
    private byte[] image;
    private java.util.Date createdAt;
    private long coordinateId;

    public Photo() {
    }

    public Photo(Long id) {
        this.id = id;
    }

    public Photo(Long id, String annotation, byte[] image, java.util.Date createdAt, long coordinateId) {
        this.id = id;
        this.annotation = annotation;
        this.image = image;
        this.createdAt = createdAt;
        this.coordinateId = coordinateId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAnnotation() {
        return annotation;
    }

    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }

    /** Not-null value. */
    public byte[] getImage() {
        return image;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImage(byte[] image) {
        this.image = image;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public long getCoordinateId() {
        return coordinateId;
    }

    public void setCoordinateId(long coordinateId) {
        this.coordinateId = coordinateId;
    }

    public String toString(){
        return "ID: " + id + " - Annotation: " + annotation + " - CoordinateID: " + coordinateId;
    }
}
