package dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import entity.Coordinate;
import entity.Journey;
import entity.Photo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig journeyDaoConfig;
    private final DaoConfig coordinateDaoConfig;
    private final DaoConfig photoDaoConfig;

    private final JourneyDao journeyDao;
    private final CoordinateDao coordinateDao;
    private final PhotoDao photoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        journeyDaoConfig = daoConfigMap.get(JourneyDao.class).clone();
        journeyDaoConfig.initIdentityScope(type);

        coordinateDaoConfig = daoConfigMap.get(CoordinateDao.class).clone();
        coordinateDaoConfig.initIdentityScope(type);

        photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
        photoDaoConfig.initIdentityScope(type);

        journeyDao = new JourneyDao(journeyDaoConfig, this);
        coordinateDao = new CoordinateDao(coordinateDaoConfig, this);
        photoDao = new PhotoDao(photoDaoConfig, this);

        registerDao(Journey.class, journeyDao);
        registerDao(Coordinate.class, coordinateDao);
        registerDao(Photo.class, photoDao);
    }
    
    public void clear() {
        journeyDaoConfig.getIdentityScope().clear();
        coordinateDaoConfig.getIdentityScope().clear();
        photoDaoConfig.getIdentityScope().clear();
    }

    public JourneyDao getJourneyDao() {
        return journeyDao;
    }

    public CoordinateDao getCoordinateDao() {
        return coordinateDao;
    }

    public PhotoDao getPhotoDao() {
        return photoDao;
    }

}
